# Generated by Django 3.2 on 2021-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100)),
                ('b_year', models.IntegerField(max_length=5)),
            ],
        ),
    ]
