# Generated by Django 3.2 on 2021-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OOPS',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_name', models.CharField(max_length=100)),
                ('o_year', models.IntegerField(max_length=5)),
            ],
        ),
    ]
